### ISSUE TITLE
Issue with TA1 Hammers + Mesecons: inifinitive gravel

### ISSUE THREAD

**Issue by apilypas** [joe7575/techage#100]
I have issue in a way TA1 Hammers works: when using this tool it creates gravel from specific nodes, and I have noticed that sometimes these nodes are not destroyed as well. I have tried to automate this with Mesecons. When using Node Breakers (you can put hammers there to use it as "punch" tool) always two ores are returned: gravel and original one. As result you can produce infinitive gravel in this way. That means you can sieve it and get a lot of free ores.

I have recorded this into video, I hope it will make it a bit more clear: https://odysee.com/@g1ngercat:1/minetest_techage_mesecons_infinitive_gravel:6

**Comment by apilypas** [comment]
I think this comes from [Pipeworks](https://content.minetest.net/packages/VanessaE/pipeworks/). It is often installed together with mesecons, as it contains some very useful nodes that works together. The node breaker works as it's name says. It breaks a node in front of it, and if you put a tool inside - it will break it with that tool. I have managed to get same effect with cobble stone as well.

Also, I have noticed that if you have some cobble stone in inventory - it is getting removed one by one when node breaker works in this way. But if none left in inventory - it is getting duplicated by node breaker. I think this behavior is related to TA1 hammers (from what I see how it usually works), but node breaker manages to "catch" broken nodes before they are removed from inventory.

I agree with you that it is possible to prevent this behavior in servers, but it is hard work to track and fix many nodes working in similar ways.

In single player it will simply be option to player to choose if he/she wants to play in this way :). If you won't be able to replicate this I don't mind if you close this issue as I don't know anyone who uses this combination for infinitive gravel :)

**Comment by joe7575** [comment]
I've updated the mod, please test if bug is fixed

**Comment by apilypas** [comment]
That was fast :) I have tried the fix. I have overwritten `techage` directory contents in existing `techage_modpack` with one from `master` branch (`techage_master.zip`) (let me know if that's not correct way).

The same setup I have created with mesecons and pipeworks still duplicating cobble stone and works as before. Looks like node breaker is still able to separate both items (gravel and original node) from overall algorithm.

Also, I have checked how hammer works in manual way and it works as before - it's function isn't broken, works as expected.

**Comment by joe7575** [comment]
Ok, thanks. It looks like I have to install pipeworks to test it myself...

**Comment by joe7575** [comment]
see [f14e93e](https://github.com/joe7575/techage/commit/f14e93e17a871bb411edfd8d6e59e7f37971d3f5)

**Comment by apilypas** [comment]
Just tested this and it works now as expected:
1. When used manually hammer produces gravel
2. When hammer used in pipework nodes it works as pickaxe

Issue fixed :)
