### ISSUE TITLE
Blocks not rendering properly.

### ISSUE THREAD

**Issue by TheMalaysianDude** [joe7575/techage#107]
Some of blocks in this mod is not rendering properly for example:
![image](https://user-images.githubusercontent.com/57954772/209777124-f798dc9b-cf40-4030-b149-f554aae1b255.png)

Solution:
Add `paramtype = "light",`  to the node that wasn't rendered properly

~personally i would pr the fix but theres so many block~

**Comment by TheMalaysianDude** [comment]
> How can I reproduce that?

Try placing TA1 melter block and see if it renders dark or not.
If it renders okay that means it's either a computer graphic card or a minetest version.

**Comment by joe7575** [comment]
> Try placing TA1 melter block and see if it renders dark or not.

I developed the mod :)  I placed all blocks many times.
I am running a public Techage server since 4 years. The Techage block number counter is currently > 700000. I had hundreds of players in the meantime. But nobody reported a bug like this with one exception on YT (Nihan Ahmed)

**Comment by TheMalaysianDude** [comment]
> > Try placing TA1 melter block and see if it renders dark or not.
> 
> I developed the mod :) I placed all blocks many times. I am running a public Techage server since 4 years. The Techage block number counter is currently > 700000. I had hundreds of players in the meantime. But nobody reported a bug like this with one exception on YT (Nihan Ahmed)

What's the version of your minetest? Mine is 5.6.0 .
Because this visual bug can be fixed.

**Comment by joe7575** [comment]
I use 5.4.1 and 5.6.0

**Comment by TheMalaysianDude** [comment]
> I use 5.4.1 and 5.6.0

I use 5.6.0.
It seems that it is my computer that's causing the problem.
~or its just the version for techage is old cus i got it from minetest menu~

**Comment by joe7575** [comment]
There are a number of YOUTUBE videos (https://www.youtube.com/watch?v=tauxw-iVkro) and this guy is also having trouble with some techage blocks. I think this is a problem with the PGN texture files.

Are you able to load the textures files ("techage_collider_magnet.png" and "techage_collider_magnet_appl.png") into your favourite image editor and store them again? Perhaps this helps. If so, I will try do change the files.

**Comment by TheMalaysianDude** [comment]
> There are a number of YOUTUBE videos (https://www.youtube.com/watch?v=tauxw-iVkro) and this guy is also having trouble with some techage blocks. I think this is a problem with the PGN texture files.
> 
> Are you able to load the textures files ("techage_collider_magnet.png" and "techage_collider_magnet_appl.png") into your favourite image editor and store them again? Perhaps this helps. If so, I will try do change the files.

I apologize for the late reply, but that didn't work.
But as I said before this visual bug can be fixed by giving the block `paramtype = "light"` into it.
https://i.imgur.com/wkebkuT.gif

**Comment by joe7575** [comment]
Thanks for your help and effort. Bug should be fixed, now.
