### ISSUE TITLE
4100 blocks traveled, yet no papyrus found

### ISSUE THREAD

**Issue by komunre** [joe7575/techage#114]
I have feeling something might be wrong with generation. I have traveled 4000 blocks, visited pine forest, oak forest, oak and birch forest, jungles, plains, savanna and winter pine forest, resulting in 7 biomes visited in total, but I did notice papyrus in none of them.
At this point, I don't even know where to search for it.

Can someone give a hint maybe? If, of course, this is not some kind of bug.

**Comment by joe7575** [comment]
I generated a V7 map with seed 1. This is the result, found in a few minutes:
![screenshot_20230116_182030](https://user-images.githubusercontent.com/17710938/212735746-548523aa-dfc2-48b4-95ed-26b6ca781738.png)

**Comment by komunre** [comment]
tried it with a seed of `1`, it generated papyrus around 200 blocks away from spawn, so indeed seems to be an unlucky seed

**Comment by komunre** [comment]
also found it on the initial world, after a bit more traveling.

**Comment by joe7575** [comment]
Thanks for your response.
