### ISSUE TITLE
digtron/battery.lua:33: in function 'count_coal'

### ISSUE THREAD

**Issue by Festus1965** [joe7575/techage#115]
2023-01-29 06:43:46: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'xtraores' in callback item_OnPlace(): .../thomas/minetest/bin/../mods/techage/digtron/battery.lua:33: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
 	[C]: in function 'pairs'
 	.../thomas/minetest/bin/../mods/techage/digtron/battery.lua:33: in function 'count_coal'
 	.../thomas/minetest/bin/../mods/techage/digtron/battery.lua:43: in function 'formspec'
 	.../thomas/minetest/bin/../mods/techage/digtron/battery.lua:155: in function 'on_rightclick'
 	/home/thomas/minetest/bin/../builtin/game/item.lua:455: in function </home/thomas/minetest/bin/../builtin/game/item.lua:448>

comment from player that crashed it:
IIIullaIII, admin server Itlay:
Low techage battery left attached to the digtron, and made to work with coal, if the fuel count problem cannot be solved, I recommend adding the message "remove low battery" to the digtron stop phase

**Comment by joe7575** [comment]
@Thomas--S Any better solution?

**Comment by Thomas--S** [comment]
I think your fix is perfect, we can probably close this issue.
