### ISSUE TITLE
Texture flip for turbine

### ISSUE THREAD

**Issue by 209CATrus** [joe7575/techage#116]
Perhaps i'm a bit late, but replace lines 85 and 108 of TA3 turbine with this

"techage_filling_ta3.png^techage_appl_turbine.png^[transformFX^techage_frame_ta3.png",

image = "techage_filling4_ta3.png^techage_appl_turbine4.png^**[transformFX**^techage_frame4_ta3.png"

So it looks adequate from both sides

**Comment by 209CATrus** [comment]
Not sure if there are other machines that might have these cosmetic defects

**Comment by 209CATrus** [comment]
The same goes for the line 85

**Comment by joe7575** [comment]
Thanks for the hint.
