### ISSUE TITLE
critical engine crash due autocrafter

### ISSUE THREAD

**Issue by Niklp09** [joe7575/techage#117]
Memory access error (memory dump written) / Speicherzugriffsfehler (Speicherabzug geschrieben) (**139/SIGSEGV**)
This is actually just a pipeworks autocrafter problem, but Techage uses the autocrafter from pipeworks

Has occurred already 6 times on my server.

Locally reproduced [instruction](https://github.com/minetest/minetest/issues/11805#issuecomment-1268653486)

---
Releated issues:
https://github.com/minetest/minetest/issues/11805
https://gitea.your-land.de/your-land/bugtracker/issues/2816
https://github.com/pandorabox-io/pandorabox.io/issues/720

**Comment by fluxionary** [comment]
for reference, we resolved this issue on your-land by disabling dragging items from/to the "output" (craft prediction) inventory.

```lua
local def = minetest.registered_nodes["pipeworks:autocrafter"]

local old_allow_metadata_inventory_move = def.allow_metadata_inventory_move
local old_allow_metadata_inventory_put = def.allow_metadata_inventory_put
local old_allow_metadata_inventory_take = def.allow_metadata_inventory_take

minetest.override_node("pipeworks:autocrafter", {
	allow_metadata_inventory_move = function(pos, from_list, from_index, to_list, to_index, count, player)
		if from_list == "output" or "to_list" == "output" then
			return 0
		end
		return old_allow_metadata_inventory_move(pos, from_list, from_index, to_list, to_index, count, player)
	end,
	allow_metadata_inventory_put = function(pos, listname, index, stack, player)
		if listname == "output" then
			return 0
		end
		return old_allow_metadata_inventory_put(pos, listname, index, stack, player)
	end,
	allow_metadata_inventory_take = function(pos, listname, index, stack, player)
		if listname == "output" then
			return 0
		end
		return old_allow_metadata_inventory_take(pos, listname, index, stack, player)
	end,
})
```

**Comment by Niklp09** [comment]
I'm testing that currently on my server, I got the patch yesterday from Bla and Alias (and have adapted it to techage)
[anti_sigsgv.patch.txt](https://github.com/joe7575/techage/files/10725242/anti_sigsgv.patch.txt)

**Comment by debagos** [comment]
> If that's a problem, it's not just the autocrafter who's affected... also furnace, fab, etc.

Nah not only the autocrafter, it's a general bug/problem: https://github.com/minetest/minetest/pull/11882
