### ISSUE TITLE
Possible Bug in techage:ta4_display

### ISSUE THREAD

**Issue by Distributed-DeadLock** [joe7575/techage#119]
I think i just crashed the AdventureTime-Server (adv.edgy1.net) 3 times with a single line of code in the techage:ta4_sequencer:
`[1] send 18743 set 1`

18743 is the correct number of a ta4_display, the "clear" and "add" commands work flawless.

My uneducated guess is: "1" is not a valid "payload" and the "techage.display.write_row"-function in " techage/icta_controller/display.lua" is failing catastrophically.

**Comment by joe7575** [comment]
Thanks for the report, should be fixed now
