### ISSUE TITLE
Active drillbox node name

### ISSUE THREAD

**Issue by 209CATrus** [joe7575/techage#121]
I suggest renaming active drillbox node from techage:ta3_drillbox_act to techage:ta3_drillbox_on, so it becomes consistent with the rest of active node names. This might lead to compatibility issues though

**Comment by 209CATrus** [comment]
Same goes for the techage:ta3_drillbox_pas

**Comment by joe7575** [comment]
As you have already written, this jeopardizes compatibility and does not add any value
