### ISSUE TITLE
TA Furnace

### ISSUE THREAD

**Issue by acmgit** [joe7575/techage#122]
The TA Furnace seems to have trouble with the recipes.
Some recipes ends in a "Recipe-Error".
Some recipes gives a Recipe-Error when you switch and choose it new, it works.

Observed on my Server.
Techage is direct from your repository and up to date.

Greetings, Clyde.

**Comment by joe7575** [comment]
Some more info please (error message, recipes, ...)

**Comment by acmgit** [comment]
Thin Basaltglass for example gives only a recipe-error.
General all recipes ends in the first use with a recipe-error. Some recipes have the workaround to switch to another recipe and then switch back to the recipe, the furnace surprisingly works.

**Comment by acmgit** [comment]
Sorry for disturbing you, the furnace is now working fine. Don't know what is was, but it's working well.
Thank you and bye.
