### ISSUE TITLE
few ideas for TA3 (TA4)

### ISSUE THREAD

**Issue by sem-geologist** [joe7575/techage#128]
I really like how TA1 requires to build larger structures. The TA1 furnace built from cobble  scales its capabilities from how tall it is - that is so awesome! Then comes the TA2 machines which differs a lot from TA1. It catches the spirit of that technological tier as in steam age the power production and consumption was localized.  The limitations of power transmission by axles quite accurately represents that age. And then moving to TA3 feels a bit too easy (in power production). I like TA3 oil exploration and oil distilling - that is awesome... but powerplant of TA3 (Coal/oil burning)  felt severely downsized IMHO and without any challenge. The cooling part of it feels most downsized and that is one of most important parts where its scaling and efficiency has huge impact how much power the steam turbine can produce. 

1. hint: I find this mod quite educational, there could be line added to manual "that there is much lesser water consumption in TA3 boiler as it is used in closed loop, where TA2 boiler looses water bit-by-bit with every steam engine piston stroke as steam exhaust". For tech-savvy person that is obvious, but for younger generation it could be nice detail to point out. I really like the perceptible difference in these boilers.

Then comes the TA4 (I will comeback to TA3 in the moment), where building solar and wind plants requires to take localisation into consideration. It requires adoption and scaling of power sources. I.e. You can build solar plant in some distant desert, bamboo-forest, fiery (ethereal) biomes for higher efficiency, but considering transmission lines and if base is moderately warm biome ( i.e. grassland) with lets say heat of 66 (so solar panel works with 2/3 efficiency) it is easier way to put solar one third larger on the rooftop of your base, than construct the power transmission infrastructure. In case the base is constructed in the cold climate - the more distant but much more efficient solar plant then makes sense. That brings some challenges and biomes influence the technical planning and decisions. BTW, while technically heat factor to these semiconductor solar panels should not be so directly influential it kind are connected indirectly by fact that warmer climates is there where is more sun, and colder - where sun is less. Minetest has same day length independently from biome, and thus contrary to some other critics in forum, I believe heat as parameter for sol. panel efficiency is the most close minetest biome parameter for best emulation chosen.

TA5 powersource demonstrates our own struggles with future type of power source (international research programs for fusion are already running over 50 years, so shame on you who complain that TA5 experience points are produced so slowly :smile:  )

So when getting back to TA3 powersource, IMHO TA3 could present not only moving to oil and electricity, but also highlight more the centralization aspect of power production. At Steam age power production was concentrated at demanding facilities. With electricity it got possible and more efficiently to produce power in centralised way and distribute it for demanding facilities. Because of centralization such power plant had to scale-up a lot compared to localized power production steam based facilities, and thus power plants are big. In steam engine we have steam generation and engine (power generator). In turbine based power generation we have actually three crucial parts: steam generator, turbine and cooler. Cooling is a crucial piece in this chain as it: 1) sustains the  pressure difference across the turbine - the bigger pressure difference the more power can be delivered to turbine; 2) in closed loop systems cooler cools down the steam to liquid water so that pumping it back to boiler would require much less energy, than compressing the steam into boiler. The first known powerplants used river, lake, sea water for cooling the steam (or simply used water and released steam to water), where later plants due to regulations and situation (arid climate without plenty of water) developed closed loop cooling systems. These systems can be divided into two categories: condensing cooling towers and dry air-cooled. Arid climate powerplants use the second one. Currently implemented cooling unit looks like one.

2. So my idea is that cooling should not be so simple. At high humidity biomes ideally it could be nice challenge to build up cooling condensation towers as a cooling device. i.e. it could could reuse TA4 inlet used for Gravel based thermal storage of TA4, and it could be built from concrete. Round structures are hard to build in voxel-based game thus this is challenging to make (design, and follow design to build it). Maybe more square like structure could be built.
The bottom part should be filled with water (and outlet leading back to boiler would be there) where intake would be placed somewhere at height of 3. Cooling tower game wise could be alternatively maybe built from baked stone... but it rather is feature between TA3-TA4 as historically those appeared because of stricting regulations and increasing efficiency. Cooling tower would reward turbine to get up to 100ku (instead of current 80ku).

4. In more arid biomes condensing towers would not work and dry air coolers should be used, where heat would decide how big array should be to get full turbine power (80ku). Arctic could work with one cooling unit, and hot biomes with array of 20-50 units. In hot climats using single cooling block would produce very little power (i.e. 5ku). Probably humidity should also take part in the equation.

5. Even if discarding completely above points 3. and 4. , it would be nice if cooling unit would require open air above and below. 

6. IRL steam turbines are much more slower to start up than steam engine, Starting stopping steam turbine  in powerplant can take a day. I think this could be tweaked a bit in techage too. I saw some of players overuse oil plants as backup solution, which is not so simple IRL. If there is no demand and such plant needs to be ready for on-demand use it can't be shutdown completely, it needs still to run on in some semi stand-by mode (the turbine should not cool-down).

7. I think if time for startup of coal/fire turbines would be increased that would make niche for additional power generator: TA3/TA4 Gas turbine - the gas turbine would directly intake and burn gases (hydrogen, propane or isopropane), and directly give power to  generator (TA3 or TA4), however differently than Oil/Coal steam turbine it would produce only 40ku as gas turbines are known to be much less efficient than steam turbines. Also its start up speed should be faster than TA2 and current TA3 boiler strartup speed. Gas turbines IRL are used more like backup solution in power networks than coal/oil plants as gas turbine is easier to start and stop. Also Gas turbine could be controlled by beduino, and all kind of logical controllers, so it would be more like TA4 than TA3 actually. Also Gas turbine requires no cooling, so it takes much less space (basically it is turbine + generator). Startup of Gas turbine requires some power (i.e. 5ku). IRL gas turbines require some initial energy to compress air before ignition.

Sorry for such long post.

**Comment by sem-geologist** [comment]
implementing steam cooling logic I think is a lot of work, I think at least increasing startup time of oil/coal plant and adding gas turbines would bring some nice addition.

**Comment by joe7575** [comment]
Thanks for your huge report.  These are very good ideas. 

The challenge is to change the assembly and/or behaviour without breaking the compatibility to running plants.
But there are certainly ways and possibilities.

There is a repo for (techage_feature_requests)[https://github.com/joe7575/techage_feature_requests].
I will take over your proposals to discuss it there more in detail.

**Comment by joe7575** [comment]
See:
https://github.com/joe7575/techage_feature_requests/issues/67
https://github.com/joe7575/techage_feature_requests/issues/68
https://github.com/joe7575/techage_feature_requests/issues/69
https://github.com/joe7575/techage_feature_requests/issues/70
