### ISSUE TITLE
Wind_Turbine

### ISSUE THREAD

**Issue by acmgit** [joe7575/techage#132]
On my server, there is a problem with this tubines.

1. There are old wind_turbines installed. They are starting and produces ku. But the ku is from second to second falling down since 0.
2. There are new wind_turbnies installed. They moving but don't produces any ku.

Don't know, why the turbines has this behaviours.

Greetings, Clyde.

**Comment by joe7575** [comment]
Energy storage almost full?
Please check the wind turbine charge termination.

**Comment by acmgit** [comment]
Yes, we checked all what we can. It looks sometime, that the network is sometime loading and next time it stops.
The Storages goes empty and will not reload.

Maybe it could help to reinstall the complete techage?

**Comment by joe7575** [comment]
No, it's probably just a wiring problem.
Replace the Electric Junction Boxes between generators and consumers/storage systems.

**Comment by acmgit** [comment]
Thx, i will try this.

**Comment by acmgit** [comment]
No, same result. The wind turbine is running, but don't produce energy. Akku are going to empty and the machines standing still.

**Comment by joe7575** [comment]
On a public server?

**Comment by acmgit** [comment]
Yes, Zeitsprung. zeitsprung.deadsoft.org port 49152

**Comment by acmgit** [comment]
Very special thanks for your visit. It seems, the problem was the value of the forcebocks in the config of the server.

Greetings,
Clyde.
