### ISSUE TITLE
Flycontroller

### ISSUE THREAD

**Issue by acmgit** [joe7575/techage#134]
In your code in file move_controller/flycontroller.lua , the constant MAX_BLOCKS will be ignored at the moving mechanism.

Set MAX_BLOCKS to 128, this has only the effect, that i can choose 128 blocks, but moving is then only with
16 blocks possible.

Greetings, Clyde.

**Comment by joe7575** [comment]
Thanks for the report. It should now be possible to set MAX_BLOCKS to 128

**Comment by acmgit** [comment]
Thx for update, i tested it again.
I setted the MAX_BLOCKS to 128.
Then i choosed 58 Blocks, 58 Blocks are stored, that was ok.
But after the command to move, only 20 Blocks are moved.

Greetings, Clyde.
