### ISSUE TITLE
Flycontroller 2

### ISSUE THREAD

**Issue by acmgit** [joe7575/techage#135]
Thx for update issue #134 , i tested it again.
I setted the MAX_BLOCKS in move_controller/flycontroller.lua to 128.
Then i choosed 58 Blocks, 58 Blocks are stored, that was ok.
But after the command to move, only 20 Blocks are moved.

Greetings, Clyde.

**Comment by joe7575** [comment]
I can't reproduce your problem.
In the following video I move 27 or 28 blocks without any issue: https://www.youtube.com/shorts/Y0FMfFDnVfo

**Comment by acmgit** [comment]
i tested it again.
A wall, vertical with one block, no problem, it stores all and moves all.
Horizontal and maybe mixed with vertical, stores all blocks, but sometimes it moves all, sometimes not.
It changes when you choose new ord old blocks.

**Comment by joe7575** [comment]
OK, not all types on nodes can be moved. For example, you can't move techage blocks with numbers or other "more complex" blocks.

**Comment by acmgit** [comment]
I only used default blocks, because is was known that not all blocks are supported.
In my case it was defaut:dry_dirt with and without grass.

**Comment by joe7575** [comment]
Do you use the mod "cottages"?
This mod modifies the dirt blocks and adds the function "after_dig_node" which elevates the dirt block to the class of "more complex" blocks.

**Comment by acmgit** [comment]
Yes, cottages is installed, but i used default:dry_dirt and default:stone. Since 5.0 are the is dry_dirt as block in normal present.

**Comment by acmgit** [comment]
Ok, i made the update:

When i chose at the first time, it works fine and get no message, that a block isn't moveable.
Than, i change the area with a new recording and not all blocks moves.
At the third time, i changed the area new, than i get the message, that there is no block to move present.

**Comment by acmgit** [comment]
More tests:
When i log in, change the area and save it, it works fine.
When i replace the node, set the area the first time, it works fine.
When i change an area, that was already set, it has problems.
When replace the node and mark nodes, which are not from default or techage, all behind the nodes will be ignored and don't move. Looks like a cut.
The test was with a barchair and an armorstand from 3d-armors. Both nodes was marked, but don't move.

No message in the chat, that the node isn't moveable.
