### ISSUE TITLE
Bug: Unable to use steam power - water buckets

### ISSUE THREAD

**Issue by pietru2004** [joe7575/techage#145]
I have used mesecraft as base game
and added following mods for small priv srv.
![obraz](https://github.com/joe7575/techage/assets/51274570/a720e801-ed47-43e5-a717-a3f1d1fa5fb1)
when I use mesecraft water bucket it does not fill the boiler, I assume that cause water bucket is not getting emptied.

**Comment by joe7575** [comment]
The bucket shouldn't even exist. In MTG the bucket recipe is overwritten. There is only the iron bucket there. This is necessary for the course of the game because there was no steel in the Iron Age. With Mesecraft you have to deactivate the Mesecraft bucket or accept that it cannot be used for techage.

**Comment by joe7575** [comment]
This should be settled, right?

**Comment by pietru2004** [comment]
![obraz](https://github.com/joe7575/techage/assets/51274570/f43ffa74-f5a6-4e35-bde6-61ebe0b1867e)
The one from TA1 Iron Ingot

**Comment by joe7575** [comment]
yes, right

**Comment by pietru2004** [comment]
so I should take water and left/right click boiler right? last time I checked water didn't disapear from my eq...

**Comment by pietru2004** [comment]
Mayby Protector Redo disallowed punch action...

**Comment by joe7575** [comment]
See https://youtu.be/Pob2JA2GBMs

**Comment by pietru2004** [comment]
I can confirm that it is not how it looks for me... when I click the boiler nothing happens for me...
I worry that If I move mesecraft_bucket to disabled_mods folder it might break something... 

Also shouldn't it be possible to punch and insert water ?
![obraz](https://github.com/joe7575/techage/assets/51274570/f7e8b846-9511-4500-bced-5c293921337a)

**Comment by pietru2004** [comment]
could mayby something like this be loaded ?
https://content.minetest.net/packages/daret/bucket/

**Comment by joe7575** [comment]
> Also shouldn't it be possible to punch and insert water ?
No, the only way is to use the iron bucket as shown on the video

**Comment by joe7575** [comment]
Does it works for you when you use minetest_game?

**Comment by pietru2004** [comment]
did not try it yet... gona make backup and check it

**Comment by joe7575** [comment]
You don't need a backup. You have to create a new world

**Comment by pietru2004** [comment]
I have made new world, enabled creative and it seams that it did not load techage... Also it is on server...

**Comment by pietru2004** [comment]
if I just download mod from contentdb and run it on singleplayer, it works, I mean just clean minetest and techage

**Comment by pietru2004** [comment]
I gona need to check is it safe to copy bucket from minetest into mesecraft

**Comment by pietru2004** [comment]
well I f-up and broke world... I guess I gona try switching to minetest as base instead of mesecraft...

**Comment by pietru2004** [comment]
I gona end this and just ask will there be support for buckets from games that are based on minetest, I mean stuff like mesecraft

**Comment by joe7575** [comment]
> will there be support for buckets from games that are based on minetest, I mean stuff like mesecraft

There is an API function to register foreign buckets to techage:

```
techage.register_water_bucket(empty_bucket, full_bucket)
```

like:

```
techage.register_water_bucket("mesecraft_bucket:bucket_empty", "mesecraft_bucket:bucket_water")
```

This allows to use other buckets. But the default iron bucket should always work.

**Comment by pietru2004** [comment]
Well I am thinking of just using minetest as base and just add mods that are needed... anyway thanks for info and help.

**Comment by pietru2004** [comment]
If I stay at minetest I guess I just will modify lua somewhere to make it add mesecraft bucket
