### ISSUE TITLE
Sea level might not be y==1 for water inlets (very minor, solution)

### ISSUE THREAD

**Issue by gd2shoe** [joe7575/techage#147]
I caught this while trying to figure out why my water inlet wasn't working (unrelated problem; I don't think techage was at fault).  This is just something I noticed in passing, and thought you might want to know.

```
waterinlet.lua:
...
local function is_ocean(pos)
        if pos.y > 1 then
                M(pos):set_string("infotext", S("Error: Not on sea level!"))
                return false
...
```

Sea level is usually at y==1... but it doesn't have to be.  It's a mapgen setting.  For instance, it's available in the UI under All Settings-> Mapgen.  Presumably, it can be set by mods and games using set_mapgen_setting(..., override_meta=true), but I don't know of any off the top of my head that do so.

I found the following line in three different mods.  I think this is the way to go (possibly adding an "or 1" on the end, for safety):

`water_level = tonumber(minetest.get_mapgen_setting("water_level"))`

This seems to correspond to the world folder's map_meta.txt file... and happens to be "1" on my mostly generic MTG+techage file.

**Comment by joe7575** [comment]
Thank you very much for the hint.
I will change the code accordingly.
