### ISSUE TITLE
Error on load image on manual pt-BR

### ISSUE THREAD

**Issue by hephaestus-br** [joe7575/techage#158]
Hi joe7575
I made a mistake with the Portuguese translation tool, in TA2 the image link for Tubo Concetrador is in Portuguese and this is generating an image loading error.

On TA3, Sound Block, there is the same error but the link isn't in portuguese.

**Comment by joe7575** [comment]
You mean this line?:  https://github.com/joe7575/techage/blob/master/manuals/manual_ta2_pt-BR.md?plain=1#L124

I believe, I already fixed this on several positions. Or is it still wrong?

**Comment by hephaestus-br** [comment]
yes, this word "concentrador" is in portuguese, I think the right is on english, "concentrator". But the Sound block I don't know because the word is wrote correctly in english

**Comment by joe7575** [comment]
Ah, I was blind :)
Thanks for the hint. I will fix it.

**Comment by joe7575** [comment]
Is fixed [here](https://github.com/joe7575/techage/commit/aa7cdfba6e52300b7a5cf2cae8756f3c480e3d92)

**Comment by hephaestus-br** [comment]
thank you!
