### ISSUE TITLE
As a user it would be helpful to have a way to verify that forceloaded blocks are force loaded

### ISSUE THREAD

**Issue by jfanjoy** [joe7575/techage#160]
Techage defaults to a 24 blocks per player limit on force load blocks, but minetest defaults to a server wide 16 block limit. This can lead to confusion since techage will allow a player to place more blocks than the server will force load. Providing players a way to see which blocks are successfully force loaded would be handy. It might also be good to check the server limit is not less than the techage per player limit on start up and log a warning if so.

**Comment by joe7575** [comment]
> It might also be good to check the server limit is not less than the techage per player limit on start up and log a warning if so.

As far as I know, there is no way to query this.
But I will take over your PR one way or another (see #161)

**Comment by joe7575** [comment]
I guess, this can be closed
