### ISSUE TITLE
Industrial Furnace Standby mode doesn't work as expected when connected to a pump

### ISSUE THREAD

**Issue by jfanjoy** [joe7575/techage#162]
It would seem that both the furnace top and a fuel pump trigger the on_transfer callback in the furnace. If the top goes into standby mode the bottom will finish using the current unit of fuel and go into standby mode. If there is a pump pushing fuel into the furnace it will be blocked until the fuel unit is spent, but when it detects free inventory space it pushes a new unit of fuel into the furnac, it will happily burn fuel while the top remains in standby mode, and it will continue to do so until either all available fuel is spent or you stop the pump and start the furnace top so it can re-enter standby mode and shut off the furnace.

**Comment by joe7575** [comment]
Thanks for the report, bug is fixed.
