### ISSUE TITLE
It would be helpful if the TA4 terminal could be moved with the techage assembly tool

### ISSUE THREAD

**Issue by jfanjoy** [joe7575/techage#165]
The TA4 terminal appears to be a laptop, but moving it causes the buttons to lose their set value and the terminal to lose any 'connected' state that it had before picking it up. It would be cool if you could at least use the techage assembly tool to move the terminal so it could be used more like a laptop in troubleshooting. Even if the connected state was lost but shell history were preserved you could easily re-establish connections with machines if you needed to move the terminal.

**Comment by jfanjoy** [comment]
In the same vein, TA4 recipe blocks moved with the assembly tool forget all of their recipes. If you could move them and preserve the recipes that would be very helpful. Not sure if that is a separate feature request or if there is some common way to make both machines moveable with the assembly tool without losing important information.

**Comment by joe7575** [comment]
The assembly tool is not the way to go. The tool's main task is to inform Techage that a block with a Techage number is now in a different position.

If TA4 prescription blocks and TA4 terminal are to receive a kind of “non-volatile memory”, this must be added to these blocks.

**Comment by jfanjoy** [comment]
Would something like the digtron crate maybe solve the need? I'm not sure having them always remember their configuration would be useful, and having a crate or some specialized tool would keep from having to add something specific to the machine. Digtron's loaded crates even store inventory and fuel levels, but they have an associated cost which I think makes sense if you want to move a techage machine too.

**Comment by joe7575** [comment]
Now, you can move the TA4 terminal with the assembly tool.
Give it a try and let me know, if it works as expected.

**Comment by jfanjoy** [comment]
This is great work! It does exactly what I was looking for thank you.
