### ISSUE TITLE
Silo does not accept nodes in powder group.

### ISSUE THREAD

**Issue by Eternal-Study** [joe7575/techage#174]
Lines 131 &132 in silo.lua checks to see if an item entering it is in the powder group using ndef=minetest.registered_craftitems[name]. However, if a reactor recipe output contains a node, then ‘ndef’ will equal ‘nil’. Recommend adding “or minetest.registered_nodes[name]” to line 131. 

While this does not affect any of the powdered items used in the Techage mod pack, as they are all registered as craft items, it can cause confusion for mod authors, as this is not outline in the API documentation. Furthermore, it limits the ability to implement ingredients from other mods that are registered as nodes (such as the sSlt node from Farming Redo).

It should be noted that lines 31-33 perform a similar check, and may require a similar edit. However, in testing editing line 131 alone addressed the issue, so no testing involving lines 31-33 was performed.

Pull request #173 addresses this issue.

**Comment by joe7575** [comment]
Code is merged
