### ISSUE TITLE
TA3 Furnace Does not implement replacements in recipes.

### ISSUE THREAD

**Issue by Eternal-Study** [joe7575/techage#175]
TA3 Furnace Does not implement replacements in recipes.

If a recipe includes a ‘replacements’ element, the TA3 furnace does not implement it.

This can be observed by installing the techage_modpack alongside the Farming Redo mod. If the salt recipe using the default furnace is used, an empty bucket is returned, replacing the water bucket used as input. However, if the salt recipe using the TA3 furnace is used, the bucket is consumed. 

This appears to be due to the TA3 furnace code not including any provisions for placing the item indicated in the replacements element in the source inventory.

**Comment by joe7575** [comment]
This is no solution for missing "replacements" elements in techage furnace recipes but fixes the issue with the salt recipe

**Comment by Eternal-Study** [comment]
Apologies for the confusing post. I'm new to Github and still learning how it works. I only mentioned this issue in 177 since I thought that, in addition to being a useful recipe on its own, it could serve as an alternative salt recipe until a way to implement the replacement value for furnace recipes could be patched in. I did not mean to suggest it solves the issue.
