### ISSUE TITLE
Add Water to Salt recipe.

### ISSUE THREAD

**Issue by Eternal-Study** [joe7575/techage#177]
As noted in issue #174  the TA3 furnace recipe for salt consumes the bucket. Therefore a reactor recipe to create salt is proposed. Even if support for the replacements element is implemented, a reactor recipe can support the mass production of salt, which is not otherwise possible due to the empty bucket being placed in the source inventory.

In addition, the recipe can be used to transform regular water into River Water. Allowing the production of River Water outside of the valleys mapgen.

Pull request #175  implements this. Creating a Water → Salt & River Water recipe if a ‘farming:salt’ node is registered, or a Water → River Water recipe if it is not.

**Comment by joe7575** [comment]
Thanks for the  PR. The issue with the empty bucket in the TA3 furnace is also solved.
