### ISSUE TITLE
TA3 Generator

### ISSUE THREAD

**Issue by FlueTheFox** [joe7575/techage#181]
Apperantly it isnt possible to automatically fill the boiler form the TA3 generator with water. It isn't possible to connect the yellow TA pipes to it that could be used to transport liquid water. Maybe add this? would be a huge improvement to gain power.

(and i don't know how to label this as a feature request, sorry about that)

**Comment by realmineplayer** [comment]
Maybe too powerfull, since it looses less water than the TA2 machine. And you shouldn’t forget that the power generators of TA4 and TA5 don’t need water so you can upgrade to them. And don’t forget that they don’t need farmed resources for powering.

**Comment by joe7575** [comment]
As realmineplayer said, TA3 must not be too powerful. There must be a gap to TA4. Therefore, a TA3 generator must not function completely automatically
