### ISSUE TITLE
TA4 Electronic Fab

### ISSUE THREAD

**Issue by realmineplayer** [joe7575/techage#183]
For me it would be nice if all TA2/TA3 Electronic Fab recipes can be used in TA4 too.

But if it has a specific reason (not sth. like *had no time*), please tell me.

**Comment by joe7575** [comment]
This is intentional. It is not the intention of the game that old systems are dismantled and replaced by new ones.
And it is also the case in reality: old vacuum tubes cannot be manufactured on chip production systems.
