### ISSUE TITLE
Pusher eats Items.

### ISSUE THREAD

**Issue by acmgit** [joe7575/techage#47]
The Pusher has a strange behaviour:
When you push to a node, that can't take the pushed item or has no inventory, the pushed Items disappears and are lost.
I checked this, as i tried to push leaves to a compost-barrel.

Greetings, Clyde.

**Comment by joe7575** [comment]
Ok, but the seems no general fault, the pusher is ok, afaik. The compost barrel eats the items and does not return false, I guess.

**Comment by acmgit** [comment]
If the pusher works with another nodes, like wall, then it must be the barrel.

**Comment by joe7575** [comment]
Did you consider this: https://github.com/joe7575/compost/blob/183d6341e4d6ba41587ffb322cae6ac5e93f15f7/init.lua#L291

**Comment by acmgit** [comment]
Hmm, i don't know exactly, i will try it, then i can report it to you.

**Comment by acmgit** [comment]
Hi Joe,
i've tested it now.
Yes, it is, what you say: you need 4 leaves to fill up the barrel.
But, if you take only 2 leaves, fill the barrel, then the next 2 leaves, fill the barrel, the barrel is empty.
Take again 2 leaves and fill the barrel, it seems to work.
As result, you need then 6 leaves to fill the barrel.

**Comment by joe7575** [comment]
I fixed it (hopefully) 
see https://github.com/joe7575/compost/commit/7153940f58910901022cec6552342a7de7b5c5f5
Thanks for reporting
