### ISSUE TITLE
Growlight

### ISSUE THREAD

**Issue by acmgit** [joe7575/techage#5]
Hallo Joe,

the Growlight works fine, but  ... ;-).

The 15% faster growing on farming-crops is really ok for the game, don't set it higher. 10 - 15% are ok.

The Flowers, that growing without anything to do are to much. If you have four or five Lights installed, you harvest the first flowerbed and if your are on the last bed, the first is full again.
Don't you thing, that you break with this behavior the balance?
Then take your Signbots, you can open a "New Holland" in less than an hour and this only one player :-D.

For me, it would be ok, that flowers growing on the special flowerbed with the speed the flowers on the green area do. You don't need a flower near to regrow it, this is a special feature and imho enough and with 15% faster growing, it's a special feature without to break the balance.
 
Greetings, Clyde.

**Comment by joe7575** [comment]
Hi Clyde,

Thanks for the feedback. I currently working on the code and will reduce the grow speed somehow. But dyes are important for many recipes and my server seems to be almost "flowers-free".

/Joe
