### ISSUE TITLE
Nuclearractor

### ISSUE THREAD

**Issue by debiankaios** [joe7575/techage#50]
In TA3 there you should can use Nuclear power. This should you give ~ 300 ku. To use Nuclear Power you need to find Uranium. Uranium will become to Plutonium-239. Uranium you should can find under y = -300. Uranium should have cracky = 1.

Done:

- [ ] Uranium
- [ ] Nuclearreactor
- [ ] Plutonium 239

**Comment by bemo5** [comment]
and if you mess up or by a chance it should  "explode or meltdown" destroying 20 nodes around it  and itself  and radiating    nodes around it for some time  and setting fire to burn able nodes  some radius around it

**Comment by joe7575** [comment]
The soon coming fusion reactor will provide ~400 ku :)
