### ISSUE TITLE
Armor ta4_jetpack:jetpack does not have "_material" specified

### ISSUE THREAD

**Issue by Ogurezzz** [joe7575/techage#54]
During load a Warning appears:
Minetest 5.4.0
`2021-03-12 13:32:43: [Main]: warning:[3d_armor] Registered armor ta4_jetpack:jetpack does not have "_material" specified at the end of the item registration name`

**Comment by joe7575** [comment]
This is the wrong repository.
But even for ta4_jetpack I don't understand the warning.

**Comment by Ogurezzz** [comment]
It is very strange thing, because jetpack appears and work  correctly... So, you can close this issue.
