### ISSUE TITLE
Chemical Reaktor

### ISSUE THREAD

**Issue by acmgit** [joe7575/techage#74]
swaps on some recipes the Output between Tank and Silo. The solution now is, you build an additional reactor. Perhaps you can fix this.

**Comment by joe7575** [comment]
The solution is you reassemble the reactor, or you could use values to control the liquid flow.

**Comment by acmgit** [comment]
Before i reassemble, i build a second ;-).
Values to control, where?

**Comment by joe7575** [comment]
sorry, I mean valves (Ventile)

**Comment by acmgit** [comment]
Oh, this could be a good idea ;-).

**Comment by acmgit** [comment]
True, i've tested the valves, this is a good way for the chemical reactor. Thx for all. I close now this issue.
