### ISSUE TITLE
Autobahn 5.5.0

### ISSUE THREAD

**Issue by vkaltschmidt** [joe7575/techage#78]
the mod autobahn seems not to work on a 5.5.0 server ?

**Comment by joe7575** [comment]
Can't confirm. The server [Zeitsprung](http://www.deadsoft.org/) is a 5.5 server and the autobahn mod works as expected.
Do you have more info, what is not working?

**Comment by vkaltschmidt** [comment]
Hi Joe thx for your Answer.
My Server is "Schwarzwald-Server". I have only the Autobahn mod without TechAge, its not working.
I try it also on a single server on 5.4. it works fine, on the 5.5 server not. Is there something i have to set or another mod i need for ?

**Comment by Niklp09** [comment]
I can help you

**Comment by joe7575** [comment]
I've tested the mod without techage. Works as expected. 
Please provide more info! 
@Niklp09 Can you give me some hint?

**Comment by Niklp09** [comment]
maybe an incompatibility with another mod

**Comment by vkaltschmidt** [comment]
yep, its the christmas mod. i activate it and then the Autobahn dosent work. For the moment i have no clue why, but i search for the problem

**Comment by Niklp09** [comment]
i think we can close it
