### ISSUE TITLE
recipies that rely on dirt do not work with biomes added by mods (Ethereal)

### ISSUE THREAD

**Issue by revulent** [joe7575/techage#8]
for example, the function that determines if dirt is placed around the lighter for the charcoal pit 

```
-- determine the number of nodes nodes (around wood)
local function num_dirt(pos)
	local pos1 = {x=pos.x-2, y=pos.y-1, z=pos.z-2}
	local pos2 = {x=pos.x+2, y=pos.y+3, z=pos.z+2}
	local nodes = minetest.find_nodes_in_area(pos1, pos2, {"default:dirt", "default:dirt_with_grass", 
			"default:dirt_with_dry_grass", "default:dirt_with_snow", "techage:dirt_with_ash"})
	return #nodes
end
```

Since it looks specifically for grass used in the default mod and not anything else, charcoal pits made in biomes added by mods break because grass will grow on the exposed sections of dirt. I suggest changing this to use the crumbly group or manually checking for popular mods that add biomes such as ethereal.

**Comment by joe7575** [comment]
the charcoal pile issue is fixed
