### ISSUE TITLE
items of a (more) 4*2000 chests are gone !

### ISSUE THREAD

**Issue by Festus1965** [joe7575/techage#80]
AS I am just start build it on my server
Asia Thailand, and have a huge base on server techage also = practice

this is new, 
first yesterday one chest used for default tree items was empty, but I know I moved them
today just after build and filled 3 other chest I came later to fill up more found items, but this 3 area empty.

I never had this problem on techage server, but this is also 2 years ago.

Viedo: of build
https://youtu.be/TGMytzecSoI

**Comment by Festus1965** [comment]
I have no any idea how,a s I build first long row of ready crafted chests, ... 
then connected them all with tubes to the backside distributor and 
filled them all step by step on most the same way
go one item family like default tree, take as much possible into inventory, and fill up the new techage 4*2000,

so there is no difference to the just right position others, but they are still full. 1st lost

And today same again ... but here this 3 until Papyrus was the last 3 to 4 I filled, and after find more in autocrafter, and bring them ... What ??? empty ... the others before this position have all items also

**Comment by Festus1965** [comment]
so getting info from last 2 days, it also happen to
* 2 of my tanks with H2 ... was empty ... the 3rd was full, so can't have been transferred there
* one gamer missed 2 ays ago a chest with minerals,
* yesterday also one gamer
the only thing that seam similar : was build new and filled from old technic:chest most manual

**Comment by Festus1965** [comment]
so on gamer reported a, I think, very good story to get behind this.

He used a chest for two different marble, and granite,
but as he got another type of marble, he took granite into another chest. (1-3 Days ago)

Today the chest was again with the granite, like using a older storage data from disc, cache, ???
And the new chest with the granite was still there.

It mean, that it happen only to one or less chest, NOT all at same time. Like random chose a chest back to older state.

**Comment by joe7575** [comment]
Sounds strange. Never heard something like that. And in the meantime several servers are using techage.
There seems to be something wrong with your database

**Comment by Festus1965** [comment]
please clarify what database you mean
after I changed to sqlite3 inside techage I didn't not here any complaint

and if map database ? server would not start anymore, ... so I am out of options where to look for it.

**Comment by joe7575** [comment]
> please clarify what database you mean

Yes I mean the sqlite3. If this is not written correct, the data gets lost.

> first yesterday one chest used for default tree items was empty, but I know I moved them
> today just after build and filled 3 other chest I came later to fill up more found items, but this 3 area empty.

The data of such kind of nodes is stored in RAM and written to the database (for the complete map block, that is 16x16x16 nodes) every 15 min, or when you shutdown the server.

If your server crashes in the meantime, or you kill the server without a normal shutdown, I is likely that data gets lost.

You could add a check to see, if the data is written in a regular basis by replacing the line [here](https://github.com/joe7575/techage/blob/master/basis/node_store.lua#L100) with 

`minetest.log("warning", "[TA Storage] Done")`.

The message ""[TA Storage] Done" should be written to the log file every 15 min.

**Comment by Festus1965** [comment]
3 days and 12 hours no crash or restart,

just paul comes back in, missing a lot of douglas slab wood in a combination of 6* 2*2k chests combined
but he let the tube in on last chess in the row ...
there is no push node, that might have taken them off, 
his build is spawn4 - no not even other gamer could come here take it

filled the chests up just yesterday ...

and I see regular this data stored techage in log / terminal

**Comment by Festus1965** [comment]
happen to less times,
gamer don't realize or solved ...

**Comment by joe7575** [comment]
Seams not to be solved: https://forum.minetest.net/viewtopic.php?p=413321#p413321
I could provide a special version with more debug output, if you are still interested?
