### ISSUE TITLE
crash 3 diff times with place a ta5_hl_chest

### ISSUE THREAD

**Issue by Festus1965** [joe7575/techage#81]
engine 5.5.0 - gamer 5.5.0
[Mod] techage (8b0d340/22.03.2022)

first build the hyperloop ta5_hl_chest onto blank floor nothing bad
I know I have only 16 ex yet

then I build a 10 meter hyperloop cube, with both and a junction:
1. crash during set the ta5_hl_chest on one end
2. crash when try 2nd on other end
3. crash then even build this ta5_hl_tube on floor (just plastic, no connection to hyperloop items, nodes)

al same : attempt to call method 'get_node_table' (a nil value)

```
ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod '' in callback item_OnPlace(): .../thomas/minetest/bin/../mods/techage/basis/hyperloop.lua:61: 
ERROR[Main]: stack traceback:
ERROR[Main]: 	.../thomas/minetest/bin/../mods/techage/basis/hyperloop.lua:61: in function 'get_free_server_list'
ERROR[Main]: 	.../thomas/minetest/bin/../mods/techage/basis/hyperloop.lua:82: in function 'on_dropdown'
ERROR[Main]: 	/home/thomas/minetest/bin/../mods/techage/basis/submenu.lua:114: in function 'generate_formspec_substring'
ERROR[Main]: 	/home/thomas/minetest/bin/../mods/techage/basis/submenu.lua:244: in function 'formspec'
ERROR[Main]: 	...inetest/bin/../mods/techage/basic_machines/ta5_chest.lua:95: in function 'after_place_node'
ERROR[Main]: 	/home/thomas/minetest/bin/../builtin/game/item.lua:414: in function </home/thomas/minetest/bin/../builtin/game/item.lua:293>
```

**Comment by Festus1965** [comment]
I did a 4th crash,
made an existing working hyper-loop route with 2 end-stations, seen, found,
and tried to place the ta5_hl_chest on a side junction, beside the way, near storage I wanted

crash same

**Comment by joe7575** [comment]
It is unclear, what happened. But I have added some additional checks. So, give it a try...

**Comment by Festus1965** [comment]
took full mod techage new, as of the new issue crash and set it active
will see soon ... thanks so far

**Comment by joe7575** [comment]
please try it again

**Comment by Festus1965** [comment]
use code 3309316 / 8 hours ago
but only copied the changed folders: basis into installation,
restart

result : no crash when build, adjust or dig,
but no addressing

facts : https://youtu.be/VLkLbfIGCjY

**Comment by Festus1965** [comment]
I just see something else:
init.lua
```
elseif minetest.global_exists("hyperloop") and hyperloop.version < 2.07 then
	minetest.log("error", "[techage] Techage requires hyperloop version 2.07 or newer!")
	return
```
didn't realize I still have V2.06 running ... was starting normal !

I change to V2.08 and check again after another restart or attack crash ... haha

**Comment by joe7575** [comment]
But the techage mod should not start, if the dependencies are not fulfilled. 
I am wondering, how did you get techage up and running with hyperloop 2.06 ???

**Comment by Festus1965** [comment]
I am also wondering, I see this line, and it is still active
and as of safer and lib2 I also confused.

But it is updated, and will be active at next restart.
Then I check

Even on the testing server, where I measured the lag impact of some mods, had the same config, but there I commented safer and lib2 out, NOT hyper.

**Comment by Festus1965** [comment]
that i used at testing server:

--elseif minetest.global_exists("lcdlib") and lcdlib.version < 1.01 then
--	minetest.log("error", "[techage] Techage requires lcdlib version 1.01 or newer!")
--	return
--elseif minetest.global_exists("safer_lua") and safer_lua.version < 1.01 then
--	minetest.log("error", "[techage] Techage requires safer_lua version 1.01 or newer!")
--	return
elseif minetest.global_exists("networks") and networks.version < 0.10 then
	minetest.log("error", "[techage] Techage requires networks version 0.10 or newer!")
	return
elseif minetest.global_exists("hyperloop") and hyperloop.version < 2.07 then
	minetest.log("error", "[techage] Techage requires hyperloop version 2.07 or newer!")
	return

it run with older lcdlib and older safer_lua
but even it was active, also run with older hyperloop V2.06

let me start tomorrow morning maybe new, then I see the ta5_hl_chest

and maybe I do the test new with correct all version fixing techage world.
But for this I see even now on active server : around spawn6 near all technic and pipeworks gone = still near 70% CPU usage
and we are 5 gamer using ahrd techage now, my base full changed, and even I lett run gravel sieving like hell = techage not reach 1%
So after technic and pipeworks is off (from July) = 1 half (50% left) my server lag for sure.

So I keep going on, but will be more careful with your version fixing dependencies.

**Comment by joe7575** [comment]
You should always test with the current and compatible mod versions and check the dependencies before you open a github issue

**Comment by Festus1965** [comment]
I guess I found the problem:

first : you are using a new plus system beside dependencies : even have to check version of this dependency = new (for me)

to the problem hyperloop older version:
As hyperloop is no dependency of teechage, as only a option plus

at my hyperloop is NOT loaded before techage even set before them in world.mt, I tested.

so whatever hyperloop startes AFTER techage, and so the testing line
elseif minetest.global_exists("hyperloop") and hyperloop.version < 2.07 then
	minetest.log("error", "[techage] Techage requires hyperloop version 2.07 or newer!")
	return
run into nothing existing,

and so techage is working also with older hyperloop versions !
as it can't see techage version during its own start.

Do I add hyperloop into techage dependency, the line works and loading of techage also is stopped.

This explains why I can use V2.06 with normal needed V2.08  Version.

By the way: In the V2.07 maybe version I see added changelog 2.07 but value version was still 2.06
so also here another problem, even itself tell V2.06 it seam to be V2.07

and
**problem solved**
after restart server with V2.08 ta5_hl_chest show options of net as should

you need to find out another way, maybe backwars inside hypeloop
to let check if techage is running and then itself stop hyperloop loading as of version not fixing to teachage ?

**Comment by Festus1965** [comment]
just wanted to test, but you did this:

```
-- Version for compatibility checks, see history
hyperloop.version = 2.06

if minetest.global_exists("techage") and techage.version < 0.06 then
	error("[hyperloop] Hyperloop requires techage version 0.06 or newer!")
	return
end
```

```
hyperloop.version = 2.08

if minetest.global_exists("techage") and techage.version < 0.06 then
	error("[hyperloop] Hyperloop requires techage version 0.06 or newer!")
	return
end
```

but you run into a problem I think:
you need to set needed techage version higher, to make sure updates in techage like now is to low, as techage need higher hyperloop.

Have fun

**Comment by joe7575** [comment]
Thanks for the hints, I have to check that again and perhaps I find a better solution for the dependency checking.

**Comment by Festus1965** [comment]
build and dig
does not make any problem anymore
