### ISSUE TITLE
An unhandled exception occurred: std::bad_alloc

### ISSUE THREAD

**Issue by Festus1965** [joe7575/techage#84]
I fear after it happen now every ay,

most during I try to take out items itself
after also often they lost connection

An unhandled exception occurred: std::bad_alloc
In thread 7fe869412700:
/home/thomas/minetest/src/server.cpp:86: virtual void* ServerThread::run(): A fatal error occurred: std::bad_alloc

This crash is fully new,
never before with 5.5.0
and also started just with be able to use hyperloop chest

sorry

**Comment by joe7575** [comment]
It is very unlikely that this is caused by a mod. Lua is running as sandbox without access to alloc functions and normally can't produce unhandled exception. I guess this is a Minetest engine bug. If you would be able to reproduce this, you can open an issue at https://github.com/minetest/minetest. 
I had a similar issue in the past, but I ended up not being able to isolate and reproduce the issue so that a core developer would have a chance of finding the bug.

**Comment by Festus1965** [comment]
there are only two possibilities, so far I know my changes:
* as of the much login attack I am actually using the auth.lua from LoneWolfHT, NOT a full new version og engine 5.5.0 / MGT
* or this Hyperloop chests, **as they also still refuse too often to connect or lose the connection later again**

So as the TA5 hyperloop chests make anyway problems I took all of, 
* let only 3 still working connections
* each on own separate hyperloop route = no connection to each other.

So I let it run now,
to further crash, as even wondering that today during dig all TA5 hl chest off, there as no crash, BUT I took the item spread loop off the big station network, got is much smaller so, and never tried to reconnect to chest anymore as that moment was most critical.

But in log is nothing to see, even this crash is different, as I see the terminal already server restarting before my client times out.

I will look this of a view more days, and if again - will take old auth.lua or even download and compile new full actual 5.5.0 engine and MTG.

**Comment by Festus1965** [comment]
so bad news,
I did NOT use or touch this TA5 hyperloop chest,
and today I wanted to build another route.

starting at Base, set junction, and a chest on ok,
build about 250 loop to spawn, set another second chest,
back to basis, connect them
items flow ...

continue another < 500 nodes length, both ends junction, not connected to the other one
set chest at spawn (send to), build 2nd chest at this 500 nodes distance point, 
from here to the moment I clock not sure what as ... CRAH
build not, connect did work, but usage anymore ... I see left monitor terminal restart

2022-05-12 12:57:49: ERROR[Server]: An unhandled exception occurred: std::bad_alloc
2022-05-12 12:57:49: ERROR[Server]: In thread 7f7f6a35f700:
2022-05-12 12:57:49: ERROR[Server]: /home/thomas/minetest/src/server.cpp:86: virtual void* ServerThread::run(): A fatal error occurred: std::bad_alloc

So still 5.5.0, with 5.5.0
only the auth.lua is special, but didn't show this failure in last 6 days.

**Comment by TechDudie** [comment]
> so bad news, I did NOT use or touch this TA5 hyperloop chest, and today I wanted to build another route.
> 
> starting at Base, set junction, and a chest on ok, build about 250 loop to spawn, set another second chest, back to basis, connect them items flow ...
> 
> continue another < 500 nodes length, both ends junction, not connected to the other one set chest at spawn (send to), build 2nd chest at this 500 nodes distance point, from here to the moment I clock not sure what as ... CRAH build not, connect did work, but usage anymore ... I see left monitor terminal restart
> 
> 2022-05-12 12:57:49: ERROR[Server]: An unhandled exception occurred: std::bad_alloc 2022-05-12 12:57:49: ERROR[Server]: In thread 7f7f6a35f700: 2022-05-12 12:57:49: ERROR[Server]: /home/thomas/minetest/src/server.cpp:86: virtual void* ServerThread::run(): A fatal error occurred: std::bad_alloc
> 
> So still 5.5.0, with 5.5.0 only the auth.lua is special, but didn't show this failure in last 6 days.

std::bad_alloc is c code, not lua
the error is with the minetest client/server, not with the mod

2022-05-12 12:57:49: ERROR[Server]: /home/thomas/minetest/src/server.**_cpp_**:86: virtual void* ServerThread::run(): A fatal error occurred: std::bad_alloc

**Comment by joe7575** [comment]
std::bad_alloc is c code, not lua
the error is with the minetest client/server, not with the mod

**Comment by Festus1965** [comment]
Ok thanks for the hint.
If Client does crash ... it is not interesting server or trigger a crash on the server I guess,
so the problem is the server engine alone, MAYBE triggered by some mod to need to to an allocation ?

But as I have no solution for this issue, I also can't report the issue as of BB's intention, that when I can't deliver a solution, I should not issue a problem anywhere (I am blocked)

The fun beside, since there and so far ONLY changing the TechAge mod, that error had not been seen anymore also. hmm
