### ISSUE TITLE
techage chests ( here sure 8*2k ) are empty after a jump with jumpdrive

### ISSUE THREAD

**Issue by Festus1965** [joe7575/techage#85]
tested only one time

I use jumpdrive (ships) : onboard
* solar tecahge working
* heat exchanger ==> if that near obsidian glass **gravel is hot,** stay old place after jump further
* distributor, seam to work, no lost of settings
* **chest was all empty** - so far I remember was there no crash

This I can test without any big losses if needed.

**Comment by joe7575** [comment]
Is the chest part of your spacecraft?

**Comment by Festus1965** [comment]
another video :
https://youtu.be/W63jeh92z8I

this time happen : 
* 8*2 chest items gone
* ta4 chest kept it
* no gravel lost (maybe not hot this time)
* the other one still 'spawns'

**Comment by joe7575** [comment]
**Blocks from techage, techpack, hyperloop, signs bot and others store information outside of the block. This is due to performance reasons. If you move them around, in the best case only the information get lost. In the worst case the server crashes.**
