### ISSUE TITLE
Charcoal pile doesn't start smoking after beeing unloaded

### ISSUE THREAD

**Issue by Skamiz** [joe7575/techage#9]
After beeing unloaded and loaded again (leaving and rejoining the world, for example) the smoke particle emiter fails to be placed.
Since it is the only indication of the curent state of the pile it turns the wait into geusswork which isn't enjoyable.
After some hunting around it turned out that the issue is caused by two LBMs having the same name.
Specificaly the one for  the smoke and the other for the gravel rinser. Both named "techage:update".
After making thier names distinct the smoke appeared as expected after the area was reloaded.
https://github.com/joe7575/techage/blob/master/iron_age/charcoalpile.lua#L210
https://github.com/joe7575/techage/blob/master/basic_machines/gravelrinser.lua#L335

**Comment by joe7575** [comment]
Many thanks Skamiz,
I fixed it.
