### ISSUE TITLE
Disappearing tank contents

### ISSUE THREAD

**Issue by d-stephane** [joe7575/techage#90]
Hello,

I just saw a small problem with the large tanks that can hold 4000 units of liquid.
I made the following circuit:

3 electrolyser + 3 TA4 pumps then connected to 4 large tanks.
I left my character next to the tanks all day.
After a while 3 tanks were filled to 4000, the fourth not yet full.
I then move the character more than 600 blocks away from the tanks and stay there for about an hour.
When I come back to the tanks, they are almost empty and there is nothing connected to them except the pumps that send the hydrogen. I lost almost 9000 units without understanding how.

Is there a reason or a bug?
(sorry for my bad English...)

**Comment by joe7575** [comment]
On which server do you play?

**Comment by d-stephane** [comment]
This is the server called "BlocLand" which is in version 5.6
The version of techage is the one before 2022-08-06

**Comment by joe7575** [comment]
Are you the server owner?

**Comment by d-stephane** [comment]
Yes

**Comment by d-stephane** [comment]
ok, I'll place these test blocks and see what happens
and sqlite_synchronous = 1

**Comment by d-stephane** [comment]
My issue is in the wrong repository, it concerns techage_modpack...
I placed the test block and I have many errors :+1: 
`2022-08-17 18:44:27: ERROR[Server]: [techage] Memory error at (-160,-12,974)`

**Comment by joe7575** [comment]
Ok, same as for Festus1965. Can you add the following code at the end of file `techage/basis/node_store.lua`:

```
-------------------------------------------------------------------
-- Database test function
-------------------------------------------------------------------
local Data = {1,2,3,4,5}
local key = 100000000000

local function test_data()
	local data = backend.get_mapblock_data(key)
	if data and type(data) == "table" and data[1] == Data[1] then
		Data[1] = Data[1] + 1
		minetest.log("action", "[techage] Database test ok")
	else
		minetest.log("error", "[techage] Database test error")
	end
	backend.store_mapblock_data(key, Data)
	
	minetest.after(60, test_data)
end

backend.store_mapblock_data(key, Data)
minetest.after(60, test_data)
```
and check the file `debug.txt` one hour later. There you should find lines like:

```
2022-08-17 14:26:49: ACTION[Server]: [techage] Database test ok
2022-08-17 14:26:49: ERROR[Server]: [techage] Database test error
```

**Comment by d-stephane** [comment]
i have an error :
<pre>
2022-08-17 19:20:55: ERROR[Main]: ModError: Failed to load and run script from /home/stephane/minetest_5.6/bin/../mods/techage_modpack/techage/init.lua:
2022-08-17 19:20:55: ERROR[Main]: .../../mods/techage_modpack/techage/basis/nodedata_meta.lua:64: attempt to index local 'item' (a number value)
2022-08-17 19:20:55: ERROR[Main]: stack traceback:
2022-08-17 19:20:55: ERROR[Main]:       .../../mods/techage_modpack/techage/basis/nodedata_meta.lua:64: in function 'store_mapblock_data'
2022-08-17 19:20:55: ERROR[Main]:       ...bin/../mods/techage_modpack/techage/basis/node_store.lua:193: in main chunk
2022-08-17 19:20:55: ERROR[Main]:       [C]: in function 'dofile'
2022-08-17 19:20:55: ERROR[Main]:       ...inetest_5.6/bin/../mods/techage_modpack/techage/init.lua:83: in main chunk</pre>

**Comment by d-stephane** [comment]
It'ok, just wrong comment line :)

**Comment by joe7575** [comment]
Interesting, you are not using the sqlite backend, but the metadata backend. Was this your intension?

**Comment by joe7575** [comment]
Did you miss to install lsqlite? Try `luarocks  --lua-version 5.1 install lsqlite3`

**Comment by joe7575** [comment]
Please update techage from here. This commit should fix the bug

**Comment by d-stephane** [comment]
if you mean the backend parameter in he world.mt, it is set to "postgresql"

**Comment by joe7575** [comment]
No, I meant `techage_use_sqlite = true`.
The bug in the metadata backend seems to be fixed, Festus1965 has no issues anymore with lost data

**Comment by d-stephane** [comment]
I added techage_use_sqlite = true in minetest.conf and after restarting the server, i have this error about a marshal module. 
I could not find anything on the internet about this module. Do you have any information about it ?
<pre>
ACTION[Main]: Server: Shutting down
ERROR[Main]: ModError: Failed to load and run script from /home/stephane/minetest_5.6/bin/../mods/techage_modpack/techage/init.lua:
ERROR[Main]: ..../mods/techage_modpack/techage/basis/nodedata_sqlite.lua:31: module 'marshal' not found:
ERROR[Main]:       no field package.preload['marshal']
ERROR[Main]:       no file './marshal.lua'
ERROR[Main]:       no file '/usr/share/luajit-2.1.0-beta3/marshal.lua'
ERROR[Main]:       no file '/usr/local/share/lua/5.1/marshal.lua'
ERROR[Main]:       no file '/usr/local/share/lua/5.1/marshal/init.lua'
ERROR[Main]:       no file '/usr/share/lua/5.1/marshal.lua'
ERROR[Main]:       no file '/usr/share/lua/5.1/marshal/init.lua'
ERROR[Main]:       no file './marshal.so'
ERROR[Main]:       no file '/usr/local/lib/lua/5.1/marshal.so'
ERROR[Main]:       no file '/usr/lib/x86_64-linux-gnu/lua/5.1/marshal.so'
ERROR[Main]:       no file '/usr/local/lib/lua/5.1/loadall.so'
ERROR[Main]: stack traceback:
ERROR[Main]:       [C]: in function 'require'
ERROR[Main]:       ..../mods/techage_modpack/techage/basis/nodedata_sqlite.lua:31: in main chunk
ERROR[Main]:       [C]: in function 'dofile'
ERROR[Main]:       ...bin/../mods/techage_modpack/techage/basis/node_store.lua:30: in main chunk
ERROR[Main]:       [C]: in function 'dofile'
ERROR[Main]:       ...inetest_5.6/bin/../mods/techage_modpack/techage/init.lua:83: in main chunk
</pre>

**Comment by d-stephane** [comment]
Ok, i found it : luarocks install lua-marshal
