### ISSUE TITLE
[Question] The reason to upgrade a gravel sieve

### ISSUE THREAD

**Issue by Lesya-cpp** [joe7575/techage#93]
Is TA2 Gravel Sieve faster then ancient TA1 Gravel Sieve? I've read the code (just a little) and I'm pretty sure that probabilities of getting something useful are exactly the same for both of this machines. But TA2 Gravel Sieve is more expensive and consumes the energy;
So the question is - 'what is the reason to upgrade a gravel sieve to TA2'?

**Comment by joe7575** [comment]
> So the question is - 'what is the reason to upgrade a gravel sieve to TA2'?
You are right, currently there is no.
I will probably slow down the TA1 Gravel Sieve

**Comment by Lesya-cpp** [comment]
Ok, thanks!
