### ISSUE TITLE
Fluid tanks get emptied when server idles for some time

### ISSUE THREAD

**Issue by roobre** [joe7575/techage#94]
Hey,

Some friends and I have been playing minetest with techage and we are really enjoying it so far. Thanks a lot for all the effort and though put into this! ❤️ 

Something I've noticed is that when we log out from the server and come back on the next day, all fuel tanks appear empty. I've seen this happen with tanks containing raw oil, and also the 5 derivates that come from the distillation tower. Interestingly enough, this does not happen with blocks that store and consume oil, e.g. `furnace_firebox` and `oilfirebox`. Those have their inventory intact after logging back in.

Something interesting is I cannot reproduce this behavior if I simply log out and log back in. Some time has to pass for liquids to disappear.

I'm using the techage_modpack release from `2022-08-06`, and techage `**2022-06-06  V1.08**`. I'm attaching my `debug.txt` although I'm not fully sure it will contain the relevant information, please ping me if you need anything else!

**Comment by roobre** [comment]
On a classic internet move I forgot the attachment on my previous post. Here it goes.
[debug.txt.gz](https://github.com/joe7575/techage/files/9610804/debug.txt.gz)

**Comment by joe7575** [comment]
Thanks for the hint. I have to update the techage_modpack ASAP.
In the meantime use the latest techage version from here (you have to update the mod [networks](https://github.com/joe7575/networks), too)
This bug was fixed on 2022-08-16 based on issue #90

**Comment by joe7575** [comment]
[techage_modpack](https://content.minetest.net/packages/joe7575/techage_modpack/) updated
